create table test.TEST_TIDB_TRANSACTION
(
   ID         long,
   VALUE    long,
   SO_DATE datetime
);

INSERT INTO  TEST_TIDB_TRANSACTION (`ID`, `VALUE`, `SO_DATE`) VALUES (1,5, sysdate());
INSERT INTO  TEST_TIDB_TRANSACTION (`ID`, `VALUE`, `SO_DATE`) VALUES (2,6, sysdate());
INSERT INTO  TEST_TIDB_TRANSACTION (`ID`, `VALUE`, `SO_DATE`) VALUES (3,7, sysdate());
INSERT INTO  TEST_TIDB_TRANSACTION (`ID`, `VALUE`, `SO_DATE`) VALUES (4,8, sysdate());
INSERT INTO  TEST_TIDB_TRANSACTION (`ID`, `VALUE`, `SO_DATE`) VALUES (5,5, sysdate());
INSERT INTO  TEST_TIDB_TRANSACTION (`ID`, `VALUE`, `SO_DATE`) VALUES (6,6, sysdate());
INSERT INTO  TEST_TIDB_TRANSACTION (`ID`, `VALUE`, `SO_DATE`) VALUES (7,7, sysdate());
INSERT INTO  TEST_TIDB_TRANSACTION (`ID`, `VALUE`, `SO_DATE`) VALUES (8,8, sysdate());
commit;